# Generated by Django 4.0.3 on 2022-06-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_app', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='explanation',
            field=models.TextField(max_length=500),
        ),
    ]
